sudo: true

language : java
jdk:
- oraclejdk8

services:
  - docker
  - postgresql
  - mysql

addons:
  apt:
    packages:
      - sshpass
    update: true

jobs:
  include:
    - stage : compile
      script: ./scripts/travis/compile.sh
    - stage : test
      before_install:
        - sudo mysql -e "use mysql; SET PASSWORD FOR 'root'@'localhost' = PASSWORD('password');FLUSH PRIVILEGES;"
        - sudo service mysql restart
        - psql -c "CREATE USER test_user WITH PASSWORD 'password' NOCREATEROLE SUPERUSER;" -U postgres
        - psql -c "CREATE DATABASE test_analytics WITH OWNER test_user;" -U postgres
        - sudo service postgresql restart
      script: ./scripts/travis/test.sh
    - stage: deploy_ZIP_to_AWS
      script: ./scripts/travis/createZipFile.sh
      deploy:
        provider: s3
        access_key_id:
          secure: $AWS_SECURE_ACCESS_KEY_ID
        secret_access_key:
          secure: $AWS_SECURE_ACCESS_KEY
        bucket: bahmni-mart
        skip_cleanup: true
        local-dir: ./build/artifacts
        upload-dir: travis-builds
        acl: public_read
    - stage: deploy_RPM_to_AWS
      script: ./scripts/travis/createRpm.sh
      deploy:
        provider: s3
        access_key_id:
          secure: $AWS_SECURE_ACCESS_KEY_ID
        secret_access_key:
          secure: $AWS_SECURE_ACCESS_KEY
        bucket: bahmni-mart
        skip_cleanup: true
        local-dir: ./build/distributions
        upload-dir: rpms
        acl: public_read
    - stage : buildDocker
      script: ./scripts/travis/buildDocker.sh

stages:
  - compile
  - test
  - deploy_ZIP_to_AWS
  - deploy_RPM_to_AWS
  - buildDocker
