sudo: true

language : java
jdk:
- oraclejdk8

services:
  - docker

addons:
  apt:
    packages:
    - sshpass

jobs:
  include:
    - stage : compile
      script: ./scripts/compile.sh
    - stage : test
      script: ./scripts/test.sh
    - stage : buildDocker
      script: ./scripts/buildDocker.sh

stages:
      - compile
      - test
      - buildDocker

