sudo: true

language : java
jdk:
- oraclejdk8

services:
  - docker

addons:
  apt:
    packages:
    - sshpass

jobs:
  include:
    - stage : compile
      script: ./scripts/travis/compile.sh
    - stage : test
      script: ./scripts/travis/test.sh
    - stage: deployToAWS
      script: ./scripts/travis/createArtifacts.sh
      deploy:
        provider: s3
        access_key_id:
          secure: $AWS_SECURE_ACCESS_KEY_ID
        secret_access_key:
          secure: $AWS_SECURE_ACCESS_KEY
        bucket: bahmni-mart
        skip_cleanup: true
        local-dir: ./build/artifacts
        upload-dir: travis-builds
        acl: public_read
    - stage : buildDocker
      script: ./scripts/travis/buildDocker.sh

stages:
  - compile
  - test
  - deployToAWS
  - buildDocker
