sudo: true

language : java
jdk:
- oraclejdk8

services:
  - docker

addons:
  apt:
    packages:
    - sshpass

jobs:
  include:
    - stage : compile
      script: ./compile.sh
    - stage : test
      script: ./test.sh
    - stage : buildDocker
      script: ./buildDocker.sh
    - stage: deploy
      script: ./deployDockerRemote.sh

stages:
      - compile
      - test
      - buildDocker
      - deploy
