dataflow-server:
    image: springcloud/spring-cloud-dataflow-server-local:1.4.0.RELEASE
    container_name: dataflow-server
    volumes:
      - /opt/bahmni-mart:/opt/bahmni-mart:rw
      - /var/www:/var/www:rw
      - /var/log:/var/log:rw
    ports:
      - "9393:9393"
    links:
      - postgres-server
    environment:
      - spring_datasource_url=jdbc:postgresql://postgres-server:5432/analytics?currentSchema=bahmni_mart_scdf
      - spring_datasource_username=analytics
      - spring_datasource_password=""
      - spring_datasource_driver-class-name=org.postgresql.Driver

postgres-server:
  image: anallytics/postgres
  volumes:
   - /var/docker-volumes/db:/var/lib/postgresql/data/:rw
  container_name: postgres-server
  ports:
   - "4432:5432"
  restart: on-failure:10
  environment:
    POSTGRES_DB_NAME: "analytics"
    ANALYTICS_DB_USER: "analytics"
