javaapp:
  image: anallytics/bahmni-mart
  container_name: mart
  ports:
    - "9393:9393"
  links:
    - postgres-server
  restart: on-failure:10
  volumes:
    - /var/www:/var/www:rw
postgres-server:
  image: anallytics/postgres
  volumes:
   - /var/docker-volumes/db:/var/lib/postgresql/data/:rw
  container_name: postgres-server
  ports:
   - "4432:5432"
  restart: on-failure:10
  environment:
    POSTGRES_DB_NAME: "analytics"
    ANALYTICS_DB_USER: "analytics"
